### ISSUE TITLE
I have a question!

### ISSUE THREAD

**Issue by v-danh** [b-Development-Team/bsharp#2]
What is the purpose of this **_bsharp_** programming language?

P.S
I hope that you will open the ```discussions``` section on Github. Thank you!

**Comment by Nv7-GitHub** [comment]
It's mostly just a fun project for me to learn about programming language/compiler development. It also helps me write complicated B* programs by type-checking large programs (kind of like TypeScript to JavaScript).

**Comment by v-danh** [comment]
> It's mostly just a fun project for me to learn about programming language/compiler development. It also helps me write complicated B* programs by type-checking large programs (kind of like TypeScript to JavaScript).

That's a great and creative idea!
